apiVersion: opni.io/v1beta1
kind: OpniCluster
metadata:
  name: cluster
spec:
  services:
    metrics:
      enabled: true
      prometheusEndpoint: # replace with your prometheus URL, for example: "http://rancher-monitoring-prometheus.cattle-monitoring-system.svc:9090"
