apiVersion: opni.io/v1beta1
kind: OpniCluster
metadata:
  name: cluster
spec:
  elastic:
    persistence:
      enabled: true
      storageClass: local-path
      accessModes:
        - ReadWriteOnce
      request: 64Gi
