apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: test-prometheus
  namespace: prometheus
spec:
  enableAdminAPI: false
  evaluationInterval: 1m
  externalUrl: http://test-prometheus.prometheus:9090
  retention: 10d
  retentionSize: 50GiB
  routePrefix: /
  shards: 1
  replicas: 1
  version: v2.27.1