# permissions for end users to view gpupolicyadapters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpupolicyadapter-viewer-role
rules:
- apiGroups:
  - opni.io
  resources:
  - gpupolicyadapters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opni.io
  resources:
  - gpupolicyadapters/status
  verbs:
  - get
