# permissions for end users to view logadapters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logadapter-viewer-role
rules:
- apiGroups:
  - opni.io.opni.io
  resources:
  - logadapters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opni.io.opni.io
  resources:
  - logadapters/status
  verbs:
  - get
