apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: metrics
  selector:
    control-plane: controller-manager
