# permissions for end users to edit opniclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opnicluster-editor-role
rules:
  - apiGroups:
      - opni.io
    resources:
      - opniclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - opni.io
    resources:
      - opniclusters/status
    verbs:
      - get
