kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opni-svc-insights
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
    resources:
      - namespaces
      - endpoints
      - deployments
      - pods
      - jobs
      - cronjobs
      - replicasets
      - daemonsets
      - statefulsets
    verbs:
      - get
      - list
      - watch
