# permissions for end users to view opniclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opnicluster-viewer-role
rules:
  - apiGroups:
      - opni.io
    resources:
      - opniclusters
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - opni.io
    resources:
      - opniclusters/status
    verbs:
      - get
