kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: svc-insights
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  - replicasets
  - daemonsets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "batch"
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
