# permissions for end users to view opnidemoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opnidemo-viewer-role
rules:
- apiGroups:
  - demo.opni.io
  resources:
  - opnidemoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.opni.io
  resources:
  - opnidemoes/status
  verbs:
  - get
