# permissions for end users to view pretrainedmodels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pretrainedmodel-viewer-role
rules:
- apiGroups:
  - opni.io
  resources:
  - pretrainedmodels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opni.io
  resources:
  - pretrainedmodels/status
  verbs:
  - get
