
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - opni.io
  resources:
  - opniclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opni.io
  resources:
  - opniclusters/finalizers
  verbs:
  - update
- apiGroups:
  - opni.io
  resources:
  - opniclusters/status
  verbs:
  - get
  - patch
  - update
