apiVersion: opni.io/v1beta1
kind: OpniCluster
metadata:
  name: opnicluster-sample
  namespace: default
spec:
  version: v0.1.2
  services:
    inference:
      image: "rancher/opni-inference-service"
      pretrainedModels:
        - name: control-plane
