apiVersion: opni.io/v1beta1
kind: OpniCluster
metadata:
  name: opnicluster-sample
  namespace: default
spec:
  version: v0.1.2
  services:
    inference:
      enabled: false
      pretrainedModels:
        - name: control-plane
  elastic:
    workloads:
      data:
        dedicatedPod: false
      client:
        dedicatedPod: false
    version: 1.13.2
  nats:
    authMethod: nkey
  s3:
    internal: {}
