apiVersion: opni.io/v1beta1
kind: OpniCluster
metadata:
  name: opnicluster-sample
  namespace: default
spec:
  version: v0.1.2
  services:
    inference:
      pretrainedModels:
        - name: pretrainedmodel-sample
  elastic:
    version: 1.13.2
  nats:
    authMethod: nkey
