apiVersion: opni.io/v1beta1
kind: OpniCluster
metadata:
  name: opnicluster-sample
  namespace: default
spec:
  version: v0.1.2
  deployLogCollector: true
  services:
    inference:
      enabled: true
      image: quay.io/dbason/opni-inference-service:test
      imagePullPolicy: Always
      pretrainedModels:
        - name: control-plane
    preprocessing:
      image: quay.io/dbason/opni-preprocessing-service:debug
    drain:
      image: quay.io/dbason/opni-drain-service:debug
    payloadReceiver:
      image: quay.io/dbason/opni-payload-receiver-service:debug
    gpuController:
      enabled: true
      image: quay.io/dbason/opni-gpu-service-controller:debug
    metrics:
      prometheusEndpoint: http://prometheus-k8s.monitoring.svc.cluster.local:9090
  elastic:
    version: 1.13.2
  nats:
    authMethod: nkey
  s3:
    internal: {}
