apiVersion: opni.io/v1beta1
kind: OpniCluster
metadata:
  name: opnicluster-sample
  namespace: default
spec:
  elastic:
    endpoint: "todo"
    credentials:
      keys:
        accessKey: testAccessKey
        secretKey: testSecretKey
