apiVersion: opni.io/v1beta1
kind: OpniCluster
metadata:
  name: opnicluster-sample
  namespace: default
spec:
  version: v0.2.0
  deployLogCollector: true
  services:
    ui:
      enabled: false
    metrics:
      enabled: true
      prometheusEndpoint: http://kube-prometheus-prometheus.monitoring.svc:9090
      prometheusNamespace: monitoring
    inference:
      pretrainedModels:
        - name: control-plane
    gpuController:
      enabled: true
  elastic:
    version: 1.13.2
  nats:
    authMethod: nkey
  s3:
    internal: {}
  thanos:
    persistence:
      enabled: true
      storageClass: local-path
      accessModes: ["ReadWriteOnce"]
      request: 10Gi
